@startwbs 買い出しWBS
title 買い出しWBS

* 買い出しに行く
**[#pink] スーパーで材料を買う
+++[#SkyBlue] 玉ねぎを買う
+++[#SkyBlue] 人参を買う
+++[#SkyBlue] じゃがいもを買う
+++[#SkyBlue] きゅうりを買う
+++[#SkyBlue] 牛肉を買う
+++[#SkyBlue] ハムを買う
+++[#SkyBlue] カレールーを買う
**[#pink] 銀行でお金をおろす
+++[#SkyBlue] 足りない場合それぞれがおろす
