@startwbs ポテトサラダを作るWBS
title ポテトサラダを作るWBS

* ポテトサラダを作る
**[#pink] 材料の下処理をする
+++[#SkyBlue] じゃがいもをつぶす
+++[#SkyBlue] 野菜を切る
+++[#SkyBlue] ハムを短冊切りにする
**[#pink] 味付け
+++[#SkyBlue] マヨネーズで和える
+++[#SkyBlue] 塩とこしょうで仕上げ