@startuml 買い出しを行くのアクティビティ図
start
fork
    #Yellow:足りない場合それぞれがおろす;
fork
    #Yellow:玉ねぎを買う;
    #Yellow:人参を買う;
    #Yellow:じゃがいもを買う;
    #Yellow:きゅうりを買う;
    #Yellow:牛肉を買う;
    #Yellow:ハムを買う;
    #Yellow:カレールーを買う;
end fork
stop
@enduml
