@startuml カレーライスを作るアクティビティ図
start
fork
    #Yellow:米を研ぐ;
    #Yellow:水を計って入れる;
    #Yellow:炊飯器で炊く;
fork again
    #Yellow:野菜を洗う;
    #Yellow:皮をむく;
    #Yellow:野菜を切る;
end fork
#Yellow:お湯を沸かす;
#Yellow:ルーを溶かす;
#Yellow:切った具を入れる;
stop
@enduml
